federation_version: =2.11.0
subgraphs:
  subgraph_1:
    routing_url: http://127.0.0.1:4001/subgraph/1
    schema:
      file: ./subgraphs/subgraph_1.graphql
  subgraph_2:
    routing_url: http://127.0.0.1:4001/subgraph/2
    schema:
      file: ./subgraphs/subgraph_2.graphql
  subgraph_3:
    routing_url: http://127.0.0.1:4001/subgraph/3
    schema:
      file: ./subgraphs/subgraph_3.graphql
  subgraph_4:
    routing_url: http://127.0.0.1:4001/subgraph/4
    schema:
      file: ./subgraphs/subgraph_4.graphql
  subgraph_5:
    routing_url: http://127.0.0.1:4001/subgraph/5
    schema:
      file: ./subgraphs/subgraph_5.graphql
  subgraph_6:
    routing_url: http://127.0.0.1:4001/subgraph/6
    schema:
      file: ./subgraphs/subgraph_6.graphql
  subgraph_7:
    routing_url: http://127.0.0.1:4001/subgraph/7
    schema:
      file: ./subgraphs/subgraph_7.graphql
  subgraph_8:
    routing_url: http://127.0.0.1:4001/subgraph/8
    schema:
      file: ./subgraphs/subgraph_8.graphql
  subgraph_9:
    routing_url: http://127.0.0.1:4001/subgraph/9
    schema:
      file: ./subgraphs/subgraph_9.graphql
  subgraph_10:
    routing_url: http://127.0.0.1:4001/subgraph/10
    schema:
      file: ./subgraphs/subgraph_10.graphql
  subgraph_11:
    routing_url: http://127.0.0.1:4001/subgraph/11
    schema:
      file: ./subgraphs/subgraph_11.graphql
  subgraph_12:
    routing_url: http://127.0.0.1:4001/subgraph/12
    schema:
      file: ./subgraphs/subgraph_12.graphql
  subgraph_13:
    routing_url: http://127.0.0.1:4001/subgraph/13
    schema:
      file: ./subgraphs/subgraph_13.graphql
  subgraph_14:
    routing_url: http://127.0.0.1:4001/subgraph/14
    schema:
      file: ./subgraphs/subgraph_14.graphql
  subgraph_15:
    routing_url: http://127.0.0.1:4001/subgraph/15
    schema:
      file: ./subgraphs/subgraph_15.graphql
  subgraph_16:
    routing_url: http://127.0.0.1:4001/subgraph/16
    schema:
      file: ./subgraphs/subgraph_16.graphql
  subgraph_17:
    routing_url: http://127.0.0.1:4001/subgraph/17
    schema:
      file: ./subgraphs/subgraph_17.graphql
  subgraph_18:
    routing_url: http://127.0.0.1:4001/subgraph/18
    schema:
      file: ./subgraphs/subgraph_18.graphql
  subgraph_19:
    routing_url: http://127.0.0.1:4001/subgraph/19
    schema:
      file: ./subgraphs/subgraph_19.graphql
  subgraph_20:
    routing_url: http://127.0.0.1:4001/subgraph/20
    schema:
      file: ./subgraphs/subgraph_20.graphql
  subgraph_21:
    routing_url: http://127.0.0.1:4001/subgraph/21
    schema:
      file: ./subgraphs/subgraph_21.graphql
  subgraph_22:
    routing_url: http://127.0.0.1:4001/subgraph/22
    schema:
      file: ./subgraphs/subgraph_22.graphql
  subgraph_23:
    routing_url: http://127.0.0.1:4001/subgraph/23
    schema:
      file: ./subgraphs/subgraph_23.graphql
  subgraph_24:
    routing_url: http://127.0.0.1:4001/subgraph/24
    schema:
      file: ./subgraphs/subgraph_24.graphql
  subgraph_25:
    routing_url: http://127.0.0.1:4001/subgraph/25
    schema:
      file: ./subgraphs/subgraph_25.graphql
  subgraph_26:
    routing_url: http://127.0.0.1:4001/subgraph/26
    schema:
      file: ./subgraphs/subgraph_26.graphql
  subgraph_27:
    routing_url: http://127.0.0.1:4001/subgraph/27
    schema:
      file: ./subgraphs/subgraph_27.graphql
  subgraph_28:
    routing_url: http://127.0.0.1:4001/subgraph/28
    schema:
      file: ./subgraphs/subgraph_28.graphql
  subgraph_29:
    routing_url: http://127.0.0.1:4001/subgraph/29
    schema:
      file: ./subgraphs/subgraph_29.graphql
  subgraph_30:
    routing_url: http://127.0.0.1:4001/subgraph/30
    schema:
      file: ./subgraphs/subgraph_30.graphql
  subgraph_31:
    routing_url: http://127.0.0.1:4001/subgraph/31
    schema:
      file: ./subgraphs/subgraph_31.graphql
  subgraph_32:
    routing_url: http://127.0.0.1:4001/subgraph/32
    schema:
      file: ./subgraphs/subgraph_32.graphql
  subgraph_33:
    routing_url: http://127.0.0.1:4001/subgraph/33
    schema:
      file: ./subgraphs/subgraph_33.graphql
  subgraph_34:
    routing_url: http://127.0.0.1:4001/subgraph/34
    schema:
      file: ./subgraphs/subgraph_34.graphql
  subgraph_35:
    routing_url: http://127.0.0.1:4001/subgraph/35
    schema:
      file: ./subgraphs/subgraph_35.graphql
  subgraph_36:
    routing_url: http://127.0.0.1:4001/subgraph/36
    schema:
      file: ./subgraphs/subgraph_36.graphql
  subgraph_37:
    routing_url: http://127.0.0.1:4001/subgraph/37
    schema:
      file: ./subgraphs/subgraph_37.graphql
  subgraph_38:
    routing_url: http://127.0.0.1:4001/subgraph/38
    schema:
      file: ./subgraphs/subgraph_38.graphql
  subgraph_39:
    routing_url: http://127.0.0.1:4001/subgraph/39
    schema:
      file: ./subgraphs/subgraph_39.graphql
  subgraph_40:
    routing_url: http://127.0.0.1:4001/subgraph/40
    schema:
      file: ./subgraphs/subgraph_40.graphql
  subgraph_41:
    routing_url: http://127.0.0.1:4001/subgraph/41
    schema:
      file: ./subgraphs/subgraph_41.graphql
  subgraph_42:
    routing_url: http://127.0.0.1:4001/subgraph/42
    schema:
      file: ./subgraphs/subgraph_42.graphql
  subgraph_43:
    routing_url: http://127.0.0.1:4001/subgraph/43
    schema:
      file: ./subgraphs/subgraph_43.graphql
  subgraph_44:
    routing_url: http://127.0.0.1:4001/subgraph/44
    schema:
      file: ./subgraphs/subgraph_44.graphql
  subgraph_45:
    routing_url: http://127.0.0.1:4001/subgraph/45
    schema:
      file: ./subgraphs/subgraph_45.graphql
  subgraph_46:
    routing_url: http://127.0.0.1:4001/subgraph/46
    schema:
      file: ./subgraphs/subgraph_46.graphql
  subgraph_47:
    routing_url: http://127.0.0.1:4001/subgraph/47
    schema:
      file: ./subgraphs/subgraph_47.graphql
  subgraph_48:
    routing_url: http://127.0.0.1:4001/subgraph/48
    schema:
      file: ./subgraphs/subgraph_48.graphql
  subgraph_49:
    routing_url: http://127.0.0.1:4001/subgraph/49
    schema:
      file: ./subgraphs/subgraph_49.graphql
  subgraph_50:
    routing_url: http://127.0.0.1:4001/subgraph/50
    schema:
      file: ./subgraphs/subgraph_50.graphql
  subgraph_51:
    routing_url: http://127.0.0.1:4001/subgraph/51
    schema:
      file: ./subgraphs/subgraph_51.graphql
  subgraph_52:
    routing_url: http://127.0.0.1:4001/subgraph/52
    schema:
      file: ./subgraphs/subgraph_52.graphql
  subgraph_53:
    routing_url: http://127.0.0.1:4001/subgraph/53
    schema:
      file: ./subgraphs/subgraph_53.graphql
  subgraph_54:
    routing_url: http://127.0.0.1:4001/subgraph/54
    schema:
      file: ./subgraphs/subgraph_54.graphql
  subgraph_55:
    routing_url: http://127.0.0.1:4001/subgraph/55
    schema:
      file: ./subgraphs/subgraph_55.graphql
  subgraph_56:
    routing_url: http://127.0.0.1:4001/subgraph/56
    schema:
      file: ./subgraphs/subgraph_56.graphql
  subgraph_57:
    routing_url: http://127.0.0.1:4001/subgraph/57
    schema:
      file: ./subgraphs/subgraph_57.graphql
  subgraph_58:
    routing_url: http://127.0.0.1:4001/subgraph/58
    schema:
      file: ./subgraphs/subgraph_58.graphql
  subgraph_59:
    routing_url: http://127.0.0.1:4001/subgraph/59
    schema:
      file: ./subgraphs/subgraph_59.graphql
  subgraph_60:
    routing_url: http://127.0.0.1:4001/subgraph/60
    schema:
      file: ./subgraphs/subgraph_60.graphql
  subgraph_61:
    routing_url: http://127.0.0.1:4001/subgraph/61
    schema:
      file: ./subgraphs/subgraph_61.graphql
  subgraph_62:
    routing_url: http://127.0.0.1:4001/subgraph/62
    schema:
      file: ./subgraphs/subgraph_62.graphql
  subgraph_63:
    routing_url: http://127.0.0.1:4001/subgraph/63
    schema:
      file: ./subgraphs/subgraph_63.graphql
  subgraph_64:
    routing_url: http://127.0.0.1:4001/subgraph/64
    schema:
      file: ./subgraphs/subgraph_64.graphql
  subgraph_65:
    routing_url: http://127.0.0.1:4001/subgraph/65
    schema:
      file: ./subgraphs/subgraph_65.graphql
  subgraph_66:
    routing_url: http://127.0.0.1:4001/subgraph/66
    schema:
      file: ./subgraphs/subgraph_66.graphql
  subgraph_67:
    routing_url: http://127.0.0.1:4001/subgraph/67
    schema:
      file: ./subgraphs/subgraph_67.graphql
  subgraph_68:
    routing_url: http://127.0.0.1:4001/subgraph/68
    schema:
      file: ./subgraphs/subgraph_68.graphql
  subgraph_69:
    routing_url: http://127.0.0.1:4001/subgraph/69
    schema:
      file: ./subgraphs/subgraph_69.graphql
  subgraph_70:
    routing_url: http://127.0.0.1:4001/subgraph/70
    schema:
      file: ./subgraphs/subgraph_70.graphql
  subgraph_71:
    routing_url: http://127.0.0.1:4001/subgraph/71
    schema:
      file: ./subgraphs/subgraph_71.graphql
  subgraph_72:
    routing_url: http://127.0.0.1:4001/subgraph/72
    schema:
      file: ./subgraphs/subgraph_72.graphql
  subgraph_73:
    routing_url: http://127.0.0.1:4001/subgraph/73
    schema:
      file: ./subgraphs/subgraph_73.graphql
  subgraph_74:
    routing_url: http://127.0.0.1:4001/subgraph/74
    schema:
      file: ./subgraphs/subgraph_74.graphql
  subgraph_75:
    routing_url: http://127.0.0.1:4001/subgraph/75
    schema:
      file: ./subgraphs/subgraph_75.graphql
  subgraph_76:
    routing_url: http://127.0.0.1:4001/subgraph/76
    schema:
      file: ./subgraphs/subgraph_76.graphql
  subgraph_77:
    routing_url: http://127.0.0.1:4001/subgraph/77
    schema:
      file: ./subgraphs/subgraph_77.graphql
  subgraph_78:
    routing_url: http://127.0.0.1:4001/subgraph/78
    schema:
      file: ./subgraphs/subgraph_78.graphql
  subgraph_79:
    routing_url: http://127.0.0.1:4001/subgraph/79
    schema:
      file: ./subgraphs/subgraph_79.graphql
  subgraph_80:
    routing_url: http://127.0.0.1:4001/subgraph/80
    schema:
      file: ./subgraphs/subgraph_80.graphql
  subgraph_81:
    routing_url: http://127.0.0.1:4001/subgraph/81
    schema:
      file: ./subgraphs/subgraph_81.graphql
  subgraph_82:
    routing_url: http://127.0.0.1:4001/subgraph/82
    schema:
      file: ./subgraphs/subgraph_82.graphql
  subgraph_83:
    routing_url: http://127.0.0.1:4001/subgraph/83
    schema:
      file: ./subgraphs/subgraph_83.graphql
  subgraph_84:
    routing_url: http://127.0.0.1:4001/subgraph/84
    schema:
      file: ./subgraphs/subgraph_84.graphql
  subgraph_85:
    routing_url: http://127.0.0.1:4001/subgraph/85
    schema:
      file: ./subgraphs/subgraph_85.graphql
  subgraph_86:
    routing_url: http://127.0.0.1:4001/subgraph/86
    schema:
      file: ./subgraphs/subgraph_86.graphql
  subgraph_87:
    routing_url: http://127.0.0.1:4001/subgraph/87
    schema:
      file: ./subgraphs/subgraph_87.graphql
  subgraph_88:
    routing_url: http://127.0.0.1:4001/subgraph/88
    schema:
      file: ./subgraphs/subgraph_88.graphql
  subgraph_89:
    routing_url: http://127.0.0.1:4001/subgraph/89
    schema:
      file: ./subgraphs/subgraph_89.graphql
  subgraph_90:
    routing_url: http://127.0.0.1:4001/subgraph/90
    schema:
      file: ./subgraphs/subgraph_90.graphql
  subgraph_91:
    routing_url: http://127.0.0.1:4001/subgraph/91
    schema:
      file: ./subgraphs/subgraph_91.graphql
  subgraph_92:
    routing_url: http://127.0.0.1:4001/subgraph/92
    schema:
      file: ./subgraphs/subgraph_92.graphql
  subgraph_93:
    routing_url: http://127.0.0.1:4001/subgraph/93
    schema:
      file: ./subgraphs/subgraph_93.graphql
  subgraph_94:
    routing_url: http://127.0.0.1:4001/subgraph/94
    schema:
      file: ./subgraphs/subgraph_94.graphql
  subgraph_95:
    routing_url: http://127.0.0.1:4001/subgraph/95
    schema:
      file: ./subgraphs/subgraph_95.graphql
  subgraph_96:
    routing_url: http://127.0.0.1:4001/subgraph/96
    schema:
      file: ./subgraphs/subgraph_96.graphql
  subgraph_97:
    routing_url: http://127.0.0.1:4001/subgraph/97
    schema:
      file: ./subgraphs/subgraph_97.graphql
  subgraph_98:
    routing_url: http://127.0.0.1:4001/subgraph/98
    schema:
      file: ./subgraphs/subgraph_98.graphql
  subgraph_99:
    routing_url: http://127.0.0.1:4001/subgraph/99
    schema:
      file: ./subgraphs/subgraph_99.graphql
  subgraph_100:
    routing_url: http://127.0.0.1:4001/subgraph/100
    schema:
      file: ./subgraphs/subgraph_100.graphql
  subgraph_101:
    routing_url: http://127.0.0.1:4001/subgraph/101
    schema:
      file: ./subgraphs/subgraph_101.graphql
  subgraph_102:
    routing_url: http://127.0.0.1:4001/subgraph/102
    schema:
      file: ./subgraphs/subgraph_102.graphql
  subgraph_103:
    routing_url: http://127.0.0.1:4001/subgraph/103
    schema:
      file: ./subgraphs/subgraph_103.graphql
  subgraph_104:
    routing_url: http://127.0.0.1:4001/subgraph/104
    schema:
      file: ./subgraphs/subgraph_104.graphql
  subgraph_105:
    routing_url: http://127.0.0.1:4001/subgraph/105
    schema:
      file: ./subgraphs/subgraph_105.graphql
  subgraph_106:
    routing_url: http://127.0.0.1:4001/subgraph/106
    schema:
      file: ./subgraphs/subgraph_106.graphql
  subgraph_107:
    routing_url: http://127.0.0.1:4001/subgraph/107
    schema:
      file: ./subgraphs/subgraph_107.graphql
  subgraph_108:
    routing_url: http://127.0.0.1:4001/subgraph/108
    schema:
      file: ./subgraphs/subgraph_108.graphql
  subgraph_109:
    routing_url: http://127.0.0.1:4001/subgraph/109
    schema:
      file: ./subgraphs/subgraph_109.graphql
  subgraph_110:
    routing_url: http://127.0.0.1:4001/subgraph/110
    schema:
      file: ./subgraphs/subgraph_110.graphql
  subgraph_111:
    routing_url: http://127.0.0.1:4001/subgraph/111
    schema:
      file: ./subgraphs/subgraph_111.graphql
  subgraph_112:
    routing_url: http://127.0.0.1:4001/subgraph/112
    schema:
      file: ./subgraphs/subgraph_112.graphql
  subgraph_113:
    routing_url: http://127.0.0.1:4001/subgraph/113
    schema:
      file: ./subgraphs/subgraph_113.graphql
  subgraph_114:
    routing_url: http://127.0.0.1:4001/subgraph/114
    schema:
      file: ./subgraphs/subgraph_114.graphql
  subgraph_115:
    routing_url: http://127.0.0.1:4001/subgraph/115
    schema:
      file: ./subgraphs/subgraph_115.graphql
  subgraph_116:
    routing_url: http://127.0.0.1:4001/subgraph/116
    schema:
      file: ./subgraphs/subgraph_116.graphql
  subgraph_117:
    routing_url: http://127.0.0.1:4001/subgraph/117
    schema:
      file: ./subgraphs/subgraph_117.graphql
  subgraph_118:
    routing_url: http://127.0.0.1:4001/subgraph/118
    schema:
      file: ./subgraphs/subgraph_118.graphql
  subgraph_119:
    routing_url: http://127.0.0.1:4001/subgraph/119
    schema:
      file: ./subgraphs/subgraph_119.graphql
  subgraph_120:
    routing_url: http://127.0.0.1:4001/subgraph/120
    schema:
      file: ./subgraphs/subgraph_120.graphql
  subgraph_121:
    routing_url: http://127.0.0.1:4001/subgraph/121
    schema:
      file: ./subgraphs/subgraph_121.graphql
  subgraph_122:
    routing_url: http://127.0.0.1:4001/subgraph/122
    schema:
      file: ./subgraphs/subgraph_122.graphql
  subgraph_123:
    routing_url: http://127.0.0.1:4001/subgraph/123
    schema:
      file: ./subgraphs/subgraph_123.graphql
  subgraph_124:
    routing_url: http://127.0.0.1:4001/subgraph/124
    schema:
      file: ./subgraphs/subgraph_124.graphql
  subgraph_125:
    routing_url: http://127.0.0.1:4001/subgraph/125
    schema:
      file: ./subgraphs/subgraph_125.graphql
  subgraph_126:
    routing_url: http://127.0.0.1:4001/subgraph/126
    schema:
      file: ./subgraphs/subgraph_126.graphql
  subgraph_127:
    routing_url: http://127.0.0.1:4001/subgraph/127
    schema:
      file: ./subgraphs/subgraph_127.graphql
  subgraph_128:
    routing_url: http://127.0.0.1:4001/subgraph/128
    schema:
      file: ./subgraphs/subgraph_128.graphql
  subgraph_129:
    routing_url: http://127.0.0.1:4001/subgraph/129
    schema:
      file: ./subgraphs/subgraph_129.graphql
  subgraph_130:
    routing_url: http://127.0.0.1:4001/subgraph/130
    schema:
      file: ./subgraphs/subgraph_130.graphql
  subgraph_131:
    routing_url: http://127.0.0.1:4001/subgraph/131
    schema:
      file: ./subgraphs/subgraph_131.graphql
  subgraph_132:
    routing_url: http://127.0.0.1:4001/subgraph/132
    schema:
      file: ./subgraphs/subgraph_132.graphql
  subgraph_133:
    routing_url: http://127.0.0.1:4001/subgraph/133
    schema:
      file: ./subgraphs/subgraph_133.graphql
  subgraph_134:
    routing_url: http://127.0.0.1:4001/subgraph/134
    schema:
      file: ./subgraphs/subgraph_134.graphql
  subgraph_135:
    routing_url: http://127.0.0.1:4001/subgraph/135
    schema:
      file: ./subgraphs/subgraph_135.graphql
  subgraph_136:
    routing_url: http://127.0.0.1:4001/subgraph/136
    schema:
      file: ./subgraphs/subgraph_136.graphql
  subgraph_137:
    routing_url: http://127.0.0.1:4001/subgraph/137
    schema:
      file: ./subgraphs/subgraph_137.graphql
  subgraph_138:
    routing_url: http://127.0.0.1:4001/subgraph/138
    schema:
      file: ./subgraphs/subgraph_138.graphql
  subgraph_139:
    routing_url: http://127.0.0.1:4001/subgraph/139
    schema:
      file: ./subgraphs/subgraph_139.graphql
  subgraph_140:
    routing_url: http://127.0.0.1:4001/subgraph/140
    schema:
      file: ./subgraphs/subgraph_140.graphql
  subgraph_141:
    routing_url: http://127.0.0.1:4001/subgraph/141
    schema:
      file: ./subgraphs/subgraph_141.graphql
  subgraph_142:
    routing_url: http://127.0.0.1:4001/subgraph/142
    schema:
      file: ./subgraphs/subgraph_142.graphql
  subgraph_143:
    routing_url: http://127.0.0.1:4001/subgraph/143
    schema:
      file: ./subgraphs/subgraph_143.graphql
  subgraph_144:
    routing_url: http://127.0.0.1:4001/subgraph/144
    schema:
      file: ./subgraphs/subgraph_144.graphql
  subgraph_145:
    routing_url: http://127.0.0.1:4001/subgraph/145
    schema:
      file: ./subgraphs/subgraph_145.graphql
  subgraph_146:
    routing_url: http://127.0.0.1:4001/subgraph/146
    schema:
      file: ./subgraphs/subgraph_146.graphql
  subgraph_147:
    routing_url: http://127.0.0.1:4001/subgraph/147
    schema:
      file: ./subgraphs/subgraph_147.graphql
  subgraph_148:
    routing_url: http://127.0.0.1:4001/subgraph/148
    schema:
      file: ./subgraphs/subgraph_148.graphql
  subgraph_149:
    routing_url: http://127.0.0.1:4001/subgraph/149
    schema:
      file: ./subgraphs/subgraph_149.graphql
  subgraph_150:
    routing_url: http://127.0.0.1:4001/subgraph/150
    schema:
      file: ./subgraphs/subgraph_150.graphql
  subgraph_151:
    routing_url: http://127.0.0.1:4001/subgraph/151
    schema:
      file: ./subgraphs/subgraph_151.graphql
  subgraph_152:
    routing_url: http://127.0.0.1:4001/subgraph/152
    schema:
      file: ./subgraphs/subgraph_152.graphql
  subgraph_153:
    routing_url: http://127.0.0.1:4001/subgraph/153
    schema:
      file: ./subgraphs/subgraph_153.graphql
  subgraph_154:
    routing_url: http://127.0.0.1:4001/subgraph/154
    schema:
      file: ./subgraphs/subgraph_154.graphql
  subgraph_155:
    routing_url: http://127.0.0.1:4001/subgraph/155
    schema:
      file: ./subgraphs/subgraph_155.graphql
  subgraph_156:
    routing_url: http://127.0.0.1:4001/subgraph/156
    schema:
      file: ./subgraphs/subgraph_156.graphql
  subgraph_157:
    routing_url: http://127.0.0.1:4001/subgraph/157
    schema:
      file: ./subgraphs/subgraph_157.graphql
  subgraph_158:
    routing_url: http://127.0.0.1:4001/subgraph/158
    schema:
      file: ./subgraphs/subgraph_158.graphql
  subgraph_159:
    routing_url: http://127.0.0.1:4001/subgraph/159
    schema:
      file: ./subgraphs/subgraph_159.graphql
  subgraph_160:
    routing_url: http://127.0.0.1:4001/subgraph/160
    schema:
      file: ./subgraphs/subgraph_160.graphql
  subgraph_161:
    routing_url: http://127.0.0.1:4001/subgraph/161
    schema:
      file: ./subgraphs/subgraph_161.graphql
  subgraph_162:
    routing_url: http://127.0.0.1:4001/subgraph/162
    schema:
      file: ./subgraphs/subgraph_162.graphql
  subgraph_163:
    routing_url: http://127.0.0.1:4001/subgraph/163
    schema:
      file: ./subgraphs/subgraph_163.graphql
  subgraph_164:
    routing_url: http://127.0.0.1:4001/subgraph/164
    schema:
      file: ./subgraphs/subgraph_164.graphql
  subgraph_165:
    routing_url: http://127.0.0.1:4001/subgraph/165
    schema:
      file: ./subgraphs/subgraph_165.graphql
  subgraph_166:
    routing_url: http://127.0.0.1:4001/subgraph/166
    schema:
      file: ./subgraphs/subgraph_166.graphql
  subgraph_167:
    routing_url: http://127.0.0.1:4001/subgraph/167
    schema:
      file: ./subgraphs/subgraph_167.graphql
  subgraph_168:
    routing_url: http://127.0.0.1:4001/subgraph/168
    schema:
      file: ./subgraphs/subgraph_168.graphql
  subgraph_169:
    routing_url: http://127.0.0.1:4001/subgraph/169
    schema:
      file: ./subgraphs/subgraph_169.graphql
  subgraph_170:
    routing_url: http://127.0.0.1:4001/subgraph/170
    schema:
      file: ./subgraphs/subgraph_170.graphql
  subgraph_171:
    routing_url: http://127.0.0.1:4001/subgraph/171
    schema:
      file: ./subgraphs/subgraph_171.graphql
  subgraph_172:
    routing_url: http://127.0.0.1:4001/subgraph/172
    schema:
      file: ./subgraphs/subgraph_172.graphql
  subgraph_173:
    routing_url: http://127.0.0.1:4001/subgraph/173
    schema:
      file: ./subgraphs/subgraph_173.graphql
  subgraph_174:
    routing_url: http://127.0.0.1:4001/subgraph/174
    schema:
      file: ./subgraphs/subgraph_174.graphql
  subgraph_175:
    routing_url: http://127.0.0.1:4001/subgraph/175
    schema:
      file: ./subgraphs/subgraph_175.graphql
  subgraph_176:
    routing_url: http://127.0.0.1:4001/subgraph/176
    schema:
      file: ./subgraphs/subgraph_176.graphql
  subgraph_177:
    routing_url: http://127.0.0.1:4001/subgraph/177
    schema:
      file: ./subgraphs/subgraph_177.graphql
  subgraph_178:
    routing_url: http://127.0.0.1:4001/subgraph/178
    schema:
      file: ./subgraphs/subgraph_178.graphql
  subgraph_179:
    routing_url: http://127.0.0.1:4001/subgraph/179
    schema:
      file: ./subgraphs/subgraph_179.graphql
  subgraph_180:
    routing_url: http://127.0.0.1:4001/subgraph/180
    schema:
      file: ./subgraphs/subgraph_180.graphql
  subgraph_181:
    routing_url: http://127.0.0.1:4001/subgraph/181
    schema:
      file: ./subgraphs/subgraph_181.graphql
  subgraph_182:
    routing_url: http://127.0.0.1:4001/subgraph/182
    schema:
      file: ./subgraphs/subgraph_182.graphql
  subgraph_183:
    routing_url: http://127.0.0.1:4001/subgraph/183
    schema:
      file: ./subgraphs/subgraph_183.graphql
  subgraph_184:
    routing_url: http://127.0.0.1:4001/subgraph/184
    schema:
      file: ./subgraphs/subgraph_184.graphql
  subgraph_185:
    routing_url: http://127.0.0.1:4001/subgraph/185
    schema:
      file: ./subgraphs/subgraph_185.graphql
  subgraph_186:
    routing_url: http://127.0.0.1:4001/subgraph/186
    schema:
      file: ./subgraphs/subgraph_186.graphql
  subgraph_187:
    routing_url: http://127.0.0.1:4001/subgraph/187
    schema:
      file: ./subgraphs/subgraph_187.graphql
  subgraph_188:
    routing_url: http://127.0.0.1:4001/subgraph/188
    schema:
      file: ./subgraphs/subgraph_188.graphql
  subgraph_189:
    routing_url: http://127.0.0.1:4001/subgraph/189
    schema:
      file: ./subgraphs/subgraph_189.graphql
  subgraph_190:
    routing_url: http://127.0.0.1:4001/subgraph/190
    schema:
      file: ./subgraphs/subgraph_190.graphql
  subgraph_191:
    routing_url: http://127.0.0.1:4001/subgraph/191
    schema:
      file: ./subgraphs/subgraph_191.graphql
  subgraph_192:
    routing_url: http://127.0.0.1:4001/subgraph/192
    schema:
      file: ./subgraphs/subgraph_192.graphql
  subgraph_193:
    routing_url: http://127.0.0.1:4001/subgraph/193
    schema:
      file: ./subgraphs/subgraph_193.graphql
  subgraph_194:
    routing_url: http://127.0.0.1:4001/subgraph/194
    schema:
      file: ./subgraphs/subgraph_194.graphql
  subgraph_195:
    routing_url: http://127.0.0.1:4001/subgraph/195
    schema:
      file: ./subgraphs/subgraph_195.graphql
  subgraph_196:
    routing_url: http://127.0.0.1:4001/subgraph/196
    schema:
      file: ./subgraphs/subgraph_196.graphql
  subgraph_197:
    routing_url: http://127.0.0.1:4001/subgraph/197
    schema:
      file: ./subgraphs/subgraph_197.graphql
  subgraph_198:
    routing_url: http://127.0.0.1:4001/subgraph/198
    schema:
      file: ./subgraphs/subgraph_198.graphql
  subgraph_199:
    routing_url: http://127.0.0.1:4001/subgraph/199
    schema:
      file: ./subgraphs/subgraph_199.graphql
  subgraph_200:
    routing_url: http://127.0.0.1:4001/subgraph/200
    schema:
      file: ./subgraphs/subgraph_200.graphql
  subgraph_201:
    routing_url: http://127.0.0.1:4001/subgraph/201
    schema:
      file: ./subgraphs/subgraph_201.graphql
  subgraph_202:
    routing_url: http://127.0.0.1:4001/subgraph/202
    schema:
      file: ./subgraphs/subgraph_202.graphql
  subgraph_203:
    routing_url: http://127.0.0.1:4001/subgraph/203
    schema:
      file: ./subgraphs/subgraph_203.graphql
  subgraph_204:
    routing_url: http://127.0.0.1:4001/subgraph/204
    schema:
      file: ./subgraphs/subgraph_204.graphql
  subgraph_205:
    routing_url: http://127.0.0.1:4001/subgraph/205
    schema:
      file: ./subgraphs/subgraph_205.graphql
  subgraph_206:
    routing_url: http://127.0.0.1:4001/subgraph/206
    schema:
      file: ./subgraphs/subgraph_206.graphql
  subgraph_207:
    routing_url: http://127.0.0.1:4001/subgraph/207
    schema:
      file: ./subgraphs/subgraph_207.graphql
  subgraph_208:
    routing_url: http://127.0.0.1:4001/subgraph/208
    schema:
      file: ./subgraphs/subgraph_208.graphql
  subgraph_209:
    routing_url: http://127.0.0.1:4001/subgraph/209
    schema:
      file: ./subgraphs/subgraph_209.graphql
  subgraph_210:
    routing_url: http://127.0.0.1:4001/subgraph/210
    schema:
      file: ./subgraphs/subgraph_210.graphql
  subgraph_211:
    routing_url: http://127.0.0.1:4001/subgraph/211
    schema:
      file: ./subgraphs/subgraph_211.graphql
  subgraph_212:
    routing_url: http://127.0.0.1:4001/subgraph/212
    schema:
      file: ./subgraphs/subgraph_212.graphql
  subgraph_213:
    routing_url: http://127.0.0.1:4001/subgraph/213
    schema:
      file: ./subgraphs/subgraph_213.graphql
  subgraph_214:
    routing_url: http://127.0.0.1:4001/subgraph/214
    schema:
      file: ./subgraphs/subgraph_214.graphql
  subgraph_215:
    routing_url: http://127.0.0.1:4001/subgraph/215
    schema:
      file: ./subgraphs/subgraph_215.graphql
  subgraph_216:
    routing_url: http://127.0.0.1:4001/subgraph/216
    schema:
      file: ./subgraphs/subgraph_216.graphql
  subgraph_217:
    routing_url: http://127.0.0.1:4001/subgraph/217
    schema:
      file: ./subgraphs/subgraph_217.graphql
  subgraph_218:
    routing_url: http://127.0.0.1:4001/subgraph/218
    schema:
      file: ./subgraphs/subgraph_218.graphql
  subgraph_219:
    routing_url: http://127.0.0.1:4001/subgraph/219
    schema:
      file: ./subgraphs/subgraph_219.graphql
  subgraph_220:
    routing_url: http://127.0.0.1:4001/subgraph/220
    schema:
      file: ./subgraphs/subgraph_220.graphql
  subgraph_221:
    routing_url: http://127.0.0.1:4001/subgraph/221
    schema:
      file: ./subgraphs/subgraph_221.graphql
  subgraph_222:
    routing_url: http://127.0.0.1:4001/subgraph/222
    schema:
      file: ./subgraphs/subgraph_222.graphql
  subgraph_223:
    routing_url: http://127.0.0.1:4001/subgraph/223
    schema:
      file: ./subgraphs/subgraph_223.graphql
  subgraph_224:
    routing_url: http://127.0.0.1:4001/subgraph/224
    schema:
      file: ./subgraphs/subgraph_224.graphql
  subgraph_225:
    routing_url: http://127.0.0.1:4001/subgraph/225
    schema:
      file: ./subgraphs/subgraph_225.graphql
  subgraph_226:
    routing_url: http://127.0.0.1:4001/subgraph/226
    schema:
      file: ./subgraphs/subgraph_226.graphql
  subgraph_227:
    routing_url: http://127.0.0.1:4001/subgraph/227
    schema:
      file: ./subgraphs/subgraph_227.graphql
  subgraph_228:
    routing_url: http://127.0.0.1:4001/subgraph/228
    schema:
      file: ./subgraphs/subgraph_228.graphql
  subgraph_229:
    routing_url: http://127.0.0.1:4001/subgraph/229
    schema:
      file: ./subgraphs/subgraph_229.graphql
  subgraph_230:
    routing_url: http://127.0.0.1:4001/subgraph/230
    schema:
      file: ./subgraphs/subgraph_230.graphql
  subgraph_231:
    routing_url: http://127.0.0.1:4001/subgraph/231
    schema:
      file: ./subgraphs/subgraph_231.graphql
  subgraph_232:
    routing_url: http://127.0.0.1:4001/subgraph/232
    schema:
      file: ./subgraphs/subgraph_232.graphql
  subgraph_233:
    routing_url: http://127.0.0.1:4001/subgraph/233
    schema:
      file: ./subgraphs/subgraph_233.graphql
  subgraph_234:
    routing_url: http://127.0.0.1:4001/subgraph/234
    schema:
      file: ./subgraphs/subgraph_234.graphql
  subgraph_235:
    routing_url: http://127.0.0.1:4001/subgraph/235
    schema:
      file: ./subgraphs/subgraph_235.graphql
  subgraph_236:
    routing_url: http://127.0.0.1:4001/subgraph/236
    schema:
      file: ./subgraphs/subgraph_236.graphql
  subgraph_237:
    routing_url: http://127.0.0.1:4001/subgraph/237
    schema:
      file: ./subgraphs/subgraph_237.graphql
  subgraph_238:
    routing_url: http://127.0.0.1:4001/subgraph/238
    schema:
      file: ./subgraphs/subgraph_238.graphql
  subgraph_239:
    routing_url: http://127.0.0.1:4001/subgraph/239
    schema:
      file: ./subgraphs/subgraph_239.graphql
  subgraph_240:
    routing_url: http://127.0.0.1:4001/subgraph/240
    schema:
      file: ./subgraphs/subgraph_240.graphql
  subgraph_241:
    routing_url: http://127.0.0.1:4001/subgraph/241
    schema:
      file: ./subgraphs/subgraph_241.graphql
  subgraph_242:
    routing_url: http://127.0.0.1:4001/subgraph/242
    schema:
      file: ./subgraphs/subgraph_242.graphql
  subgraph_243:
    routing_url: http://127.0.0.1:4001/subgraph/243
    schema:
      file: ./subgraphs/subgraph_243.graphql
  subgraph_244:
    routing_url: http://127.0.0.1:4001/subgraph/244
    schema:
      file: ./subgraphs/subgraph_244.graphql
  subgraph_245:
    routing_url: http://127.0.0.1:4001/subgraph/245
    schema:
      file: ./subgraphs/subgraph_245.graphql
  subgraph_246:
    routing_url: http://127.0.0.1:4001/subgraph/246
    schema:
      file: ./subgraphs/subgraph_246.graphql
  subgraph_247:
    routing_url: http://127.0.0.1:4001/subgraph/247
    schema:
      file: ./subgraphs/subgraph_247.graphql
  subgraph_248:
    routing_url: http://127.0.0.1:4001/subgraph/248
    schema:
      file: ./subgraphs/subgraph_248.graphql
  subgraph_249:
    routing_url: http://127.0.0.1:4001/subgraph/249
    schema:
      file: ./subgraphs/subgraph_249.graphql
  subgraph_250:
    routing_url: http://127.0.0.1:4001/subgraph/250
    schema:
      file: ./subgraphs/subgraph_250.graphql
  subgraph_251:
    routing_url: http://127.0.0.1:4001/subgraph/251
    schema:
      file: ./subgraphs/subgraph_251.graphql
  subgraph_252:
    routing_url: http://127.0.0.1:4001/subgraph/252
    schema:
      file: ./subgraphs/subgraph_252.graphql
  subgraph_253:
    routing_url: http://127.0.0.1:4001/subgraph/253
    schema:
      file: ./subgraphs/subgraph_253.graphql
  subgraph_254:
    routing_url: http://127.0.0.1:4001/subgraph/254
    schema:
      file: ./subgraphs/subgraph_254.graphql
  subgraph_255:
    routing_url: http://127.0.0.1:4001/subgraph/255
    schema:
      file: ./subgraphs/subgraph_255.graphql
  subgraph_256:
    routing_url: http://127.0.0.1:4001/subgraph/256
    schema:
      file: ./subgraphs/subgraph_256.graphql
  subgraph_257:
    routing_url: http://127.0.0.1:4001/subgraph/257
    schema:
      file: ./subgraphs/subgraph_257.graphql
  subgraph_258:
    routing_url: http://127.0.0.1:4001/subgraph/258
    schema:
      file: ./subgraphs/subgraph_258.graphql
  subgraph_259:
    routing_url: http://127.0.0.1:4001/subgraph/259
    schema:
      file: ./subgraphs/subgraph_259.graphql
  subgraph_260:
    routing_url: http://127.0.0.1:4001/subgraph/260
    schema:
      file: ./subgraphs/subgraph_260.graphql
  subgraph_261:
    routing_url: http://127.0.0.1:4001/subgraph/261
    schema:
      file: ./subgraphs/subgraph_261.graphql
  subgraph_262:
    routing_url: http://127.0.0.1:4001/subgraph/262
    schema:
      file: ./subgraphs/subgraph_262.graphql
  subgraph_263:
    routing_url: http://127.0.0.1:4001/subgraph/263
    schema:
      file: ./subgraphs/subgraph_263.graphql
  subgraph_264:
    routing_url: http://127.0.0.1:4001/subgraph/264
    schema:
      file: ./subgraphs/subgraph_264.graphql
  subgraph_265:
    routing_url: http://127.0.0.1:4001/subgraph/265
    schema:
      file: ./subgraphs/subgraph_265.graphql
  subgraph_266:
    routing_url: http://127.0.0.1:4001/subgraph/266
    schema:
      file: ./subgraphs/subgraph_266.graphql
  subgraph_267:
    routing_url: http://127.0.0.1:4001/subgraph/267
    schema:
      file: ./subgraphs/subgraph_267.graphql
  subgraph_268:
    routing_url: http://127.0.0.1:4001/subgraph/268
    schema:
      file: ./subgraphs/subgraph_268.graphql
  subgraph_269:
    routing_url: http://127.0.0.1:4001/subgraph/269
    schema:
      file: ./subgraphs/subgraph_269.graphql
  subgraph_270:
    routing_url: http://127.0.0.1:4001/subgraph/270
    schema:
      file: ./subgraphs/subgraph_270.graphql
  subgraph_271:
    routing_url: http://127.0.0.1:4001/subgraph/271
    schema:
      file: ./subgraphs/subgraph_271.graphql
  subgraph_272:
    routing_url: http://127.0.0.1:4001/subgraph/272
    schema:
      file: ./subgraphs/subgraph_272.graphql
  subgraph_273:
    routing_url: http://127.0.0.1:4001/subgraph/273
    schema:
      file: ./subgraphs/subgraph_273.graphql
  subgraph_274:
    routing_url: http://127.0.0.1:4001/subgraph/274
    schema:
      file: ./subgraphs/subgraph_274.graphql
  subgraph_275:
    routing_url: http://127.0.0.1:4001/subgraph/275
    schema:
      file: ./subgraphs/subgraph_275.graphql
  subgraph_276:
    routing_url: http://127.0.0.1:4001/subgraph/276
    schema:
      file: ./subgraphs/subgraph_276.graphql
  subgraph_277:
    routing_url: http://127.0.0.1:4001/subgraph/277
    schema:
      file: ./subgraphs/subgraph_277.graphql
  subgraph_278:
    routing_url: http://127.0.0.1:4001/subgraph/278
    schema:
      file: ./subgraphs/subgraph_278.graphql
  subgraph_279:
    routing_url: http://127.0.0.1:4001/subgraph/279
    schema:
      file: ./subgraphs/subgraph_279.graphql
  subgraph_280:
    routing_url: http://127.0.0.1:4001/subgraph/280
    schema:
      file: ./subgraphs/subgraph_280.graphql
  subgraph_281:
    routing_url: http://127.0.0.1:4001/subgraph/281
    schema:
      file: ./subgraphs/subgraph_281.graphql
  subgraph_282:
    routing_url: http://127.0.0.1:4001/subgraph/282
    schema:
      file: ./subgraphs/subgraph_282.graphql
  subgraph_283:
    routing_url: http://127.0.0.1:4001/subgraph/283
    schema:
      file: ./subgraphs/subgraph_283.graphql
  subgraph_284:
    routing_url: http://127.0.0.1:4001/subgraph/284
    schema:
      file: ./subgraphs/subgraph_284.graphql
  subgraph_285:
    routing_url: http://127.0.0.1:4001/subgraph/285
    schema:
      file: ./subgraphs/subgraph_285.graphql
  subgraph_286:
    routing_url: http://127.0.0.1:4001/subgraph/286
    schema:
      file: ./subgraphs/subgraph_286.graphql
  subgraph_287:
    routing_url: http://127.0.0.1:4001/subgraph/287
    schema:
      file: ./subgraphs/subgraph_287.graphql
  subgraph_288:
    routing_url: http://127.0.0.1:4001/subgraph/288
    schema:
      file: ./subgraphs/subgraph_288.graphql
  subgraph_289:
    routing_url: http://127.0.0.1:4001/subgraph/289
    schema:
      file: ./subgraphs/subgraph_289.graphql
  subgraph_290:
    routing_url: http://127.0.0.1:4001/subgraph/290
    schema:
      file: ./subgraphs/subgraph_290.graphql
  subgraph_291:
    routing_url: http://127.0.0.1:4001/subgraph/291
    schema:
      file: ./subgraphs/subgraph_291.graphql
  subgraph_292:
    routing_url: http://127.0.0.1:4001/subgraph/292
    schema:
      file: ./subgraphs/subgraph_292.graphql
  subgraph_293:
    routing_url: http://127.0.0.1:4001/subgraph/293
    schema:
      file: ./subgraphs/subgraph_293.graphql
  subgraph_294:
    routing_url: http://127.0.0.1:4001/subgraph/294
    schema:
      file: ./subgraphs/subgraph_294.graphql
  subgraph_295:
    routing_url: http://127.0.0.1:4001/subgraph/295
    schema:
      file: ./subgraphs/subgraph_295.graphql
  subgraph_296:
    routing_url: http://127.0.0.1:4001/subgraph/296
    schema:
      file: ./subgraphs/subgraph_296.graphql
  subgraph_297:
    routing_url: http://127.0.0.1:4001/subgraph/297
    schema:
      file: ./subgraphs/subgraph_297.graphql
  subgraph_298:
    routing_url: http://127.0.0.1:4001/subgraph/298
    schema:
      file: ./subgraphs/subgraph_298.graphql
  subgraph_299:
    routing_url: http://127.0.0.1:4001/subgraph/299
    schema:
      file: ./subgraphs/subgraph_299.graphql
  subgraph_300:
    routing_url: http://127.0.0.1:4001/subgraph/300
    schema:
      file: ./subgraphs/subgraph_300.graphql
