schema
  @link(url: "https://specs.apollo.dev/link/v1.0")
  @link(url: "https://specs.apollo.dev/join/v0.3", for: EXECUTION)
{
  query: Query
}

directive @join__enumValue(graph: join__Graph!) repeatable on ENUM_VALUE

directive @join__field(graph: join__Graph, requires: join__FieldSet, provides: join__FieldSet, type: String, external: Boolean, override: String, usedOverridden: Boolean) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__implements(graph: join__Graph!, interface: String!) repeatable on OBJECT | INTERFACE

directive @join__type(graph: join__Graph!, key: join__FieldSet, extension: Boolean! = false, resolvable: Boolean! = true, isInterfaceObject: Boolean! = false) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR

directive @join__unionMember(graph: join__Graph!, member: String!) repeatable on UNION

directive @link(url: String, as: String, for: link__Purpose, import: [link__Import]) repeatable on SCHEMA

scalar join__FieldSet

enum join__Graph {
  SUBGRAPH_1_ @join__graph(name: "subgraph_1", url: "http://127.0.0.1:4001/subgraph/1")
  SUBGRAPH_10_ @join__graph(name: "subgraph_10", url: "http://127.0.0.1:4001/subgraph/10")
  SUBGRAPH_100_ @join__graph(name: "subgraph_100", url: "http://127.0.0.1:4001/subgraph/100")
  SUBGRAPH_11_ @join__graph(name: "subgraph_11", url: "http://127.0.0.1:4001/subgraph/11")
  SUBGRAPH_12_ @join__graph(name: "subgraph_12", url: "http://127.0.0.1:4001/subgraph/12")
  SUBGRAPH_13_ @join__graph(name: "subgraph_13", url: "http://127.0.0.1:4001/subgraph/13")
  SUBGRAPH_14_ @join__graph(name: "subgraph_14", url: "http://127.0.0.1:4001/subgraph/14")
  SUBGRAPH_15_ @join__graph(name: "subgraph_15", url: "http://127.0.0.1:4001/subgraph/15")
  SUBGRAPH_16_ @join__graph(name: "subgraph_16", url: "http://127.0.0.1:4001/subgraph/16")
  SUBGRAPH_17_ @join__graph(name: "subgraph_17", url: "http://127.0.0.1:4001/subgraph/17")
  SUBGRAPH_18_ @join__graph(name: "subgraph_18", url: "http://127.0.0.1:4001/subgraph/18")
  SUBGRAPH_19_ @join__graph(name: "subgraph_19", url: "http://127.0.0.1:4001/subgraph/19")
  SUBGRAPH_2_ @join__graph(name: "subgraph_2", url: "http://127.0.0.1:4001/subgraph/2")
  SUBGRAPH_20_ @join__graph(name: "subgraph_20", url: "http://127.0.0.1:4001/subgraph/20")
  SUBGRAPH_21_ @join__graph(name: "subgraph_21", url: "http://127.0.0.1:4001/subgraph/21")
  SUBGRAPH_22_ @join__graph(name: "subgraph_22", url: "http://127.0.0.1:4001/subgraph/22")
  SUBGRAPH_23_ @join__graph(name: "subgraph_23", url: "http://127.0.0.1:4001/subgraph/23")
  SUBGRAPH_24_ @join__graph(name: "subgraph_24", url: "http://127.0.0.1:4001/subgraph/24")
  SUBGRAPH_25_ @join__graph(name: "subgraph_25", url: "http://127.0.0.1:4001/subgraph/25")
  SUBGRAPH_26_ @join__graph(name: "subgraph_26", url: "http://127.0.0.1:4001/subgraph/26")
  SUBGRAPH_27_ @join__graph(name: "subgraph_27", url: "http://127.0.0.1:4001/subgraph/27")
  SUBGRAPH_28_ @join__graph(name: "subgraph_28", url: "http://127.0.0.1:4001/subgraph/28")
  SUBGRAPH_29_ @join__graph(name: "subgraph_29", url: "http://127.0.0.1:4001/subgraph/29")
  SUBGRAPH_3_ @join__graph(name: "subgraph_3", url: "http://127.0.0.1:4001/subgraph/3")
  SUBGRAPH_30_ @join__graph(name: "subgraph_30", url: "http://127.0.0.1:4001/subgraph/30")
  SUBGRAPH_31_ @join__graph(name: "subgraph_31", url: "http://127.0.0.1:4001/subgraph/31")
  SUBGRAPH_32_ @join__graph(name: "subgraph_32", url: "http://127.0.0.1:4001/subgraph/32")
  SUBGRAPH_33_ @join__graph(name: "subgraph_33", url: "http://127.0.0.1:4001/subgraph/33")
  SUBGRAPH_34_ @join__graph(name: "subgraph_34", url: "http://127.0.0.1:4001/subgraph/34")
  SUBGRAPH_35_ @join__graph(name: "subgraph_35", url: "http://127.0.0.1:4001/subgraph/35")
  SUBGRAPH_36_ @join__graph(name: "subgraph_36", url: "http://127.0.0.1:4001/subgraph/36")
  SUBGRAPH_37_ @join__graph(name: "subgraph_37", url: "http://127.0.0.1:4001/subgraph/37")
  SUBGRAPH_38_ @join__graph(name: "subgraph_38", url: "http://127.0.0.1:4001/subgraph/38")
  SUBGRAPH_39_ @join__graph(name: "subgraph_39", url: "http://127.0.0.1:4001/subgraph/39")
  SUBGRAPH_4_ @join__graph(name: "subgraph_4", url: "http://127.0.0.1:4001/subgraph/4")
  SUBGRAPH_40_ @join__graph(name: "subgraph_40", url: "http://127.0.0.1:4001/subgraph/40")
  SUBGRAPH_41_ @join__graph(name: "subgraph_41", url: "http://127.0.0.1:4001/subgraph/41")
  SUBGRAPH_42_ @join__graph(name: "subgraph_42", url: "http://127.0.0.1:4001/subgraph/42")
  SUBGRAPH_43_ @join__graph(name: "subgraph_43", url: "http://127.0.0.1:4001/subgraph/43")
  SUBGRAPH_44_ @join__graph(name: "subgraph_44", url: "http://127.0.0.1:4001/subgraph/44")
  SUBGRAPH_45_ @join__graph(name: "subgraph_45", url: "http://127.0.0.1:4001/subgraph/45")
  SUBGRAPH_46_ @join__graph(name: "subgraph_46", url: "http://127.0.0.1:4001/subgraph/46")
  SUBGRAPH_47_ @join__graph(name: "subgraph_47", url: "http://127.0.0.1:4001/subgraph/47")
  SUBGRAPH_48_ @join__graph(name: "subgraph_48", url: "http://127.0.0.1:4001/subgraph/48")
  SUBGRAPH_49_ @join__graph(name: "subgraph_49", url: "http://127.0.0.1:4001/subgraph/49")
  SUBGRAPH_5_ @join__graph(name: "subgraph_5", url: "http://127.0.0.1:4001/subgraph/5")
  SUBGRAPH_50_ @join__graph(name: "subgraph_50", url: "http://127.0.0.1:4001/subgraph/50")
  SUBGRAPH_51_ @join__graph(name: "subgraph_51", url: "http://127.0.0.1:4001/subgraph/51")
  SUBGRAPH_52_ @join__graph(name: "subgraph_52", url: "http://127.0.0.1:4001/subgraph/52")
  SUBGRAPH_53_ @join__graph(name: "subgraph_53", url: "http://127.0.0.1:4001/subgraph/53")
  SUBGRAPH_54_ @join__graph(name: "subgraph_54", url: "http://127.0.0.1:4001/subgraph/54")
  SUBGRAPH_55_ @join__graph(name: "subgraph_55", url: "http://127.0.0.1:4001/subgraph/55")
  SUBGRAPH_56_ @join__graph(name: "subgraph_56", url: "http://127.0.0.1:4001/subgraph/56")
  SUBGRAPH_57_ @join__graph(name: "subgraph_57", url: "http://127.0.0.1:4001/subgraph/57")
  SUBGRAPH_58_ @join__graph(name: "subgraph_58", url: "http://127.0.0.1:4001/subgraph/58")
  SUBGRAPH_59_ @join__graph(name: "subgraph_59", url: "http://127.0.0.1:4001/subgraph/59")
  SUBGRAPH_6_ @join__graph(name: "subgraph_6", url: "http://127.0.0.1:4001/subgraph/6")
  SUBGRAPH_60_ @join__graph(name: "subgraph_60", url: "http://127.0.0.1:4001/subgraph/60")
  SUBGRAPH_61_ @join__graph(name: "subgraph_61", url: "http://127.0.0.1:4001/subgraph/61")
  SUBGRAPH_62_ @join__graph(name: "subgraph_62", url: "http://127.0.0.1:4001/subgraph/62")
  SUBGRAPH_63_ @join__graph(name: "subgraph_63", url: "http://127.0.0.1:4001/subgraph/63")
  SUBGRAPH_64_ @join__graph(name: "subgraph_64", url: "http://127.0.0.1:4001/subgraph/64")
  SUBGRAPH_65_ @join__graph(name: "subgraph_65", url: "http://127.0.0.1:4001/subgraph/65")
  SUBGRAPH_66_ @join__graph(name: "subgraph_66", url: "http://127.0.0.1:4001/subgraph/66")
  SUBGRAPH_67_ @join__graph(name: "subgraph_67", url: "http://127.0.0.1:4001/subgraph/67")
  SUBGRAPH_68_ @join__graph(name: "subgraph_68", url: "http://127.0.0.1:4001/subgraph/68")
  SUBGRAPH_69_ @join__graph(name: "subgraph_69", url: "http://127.0.0.1:4001/subgraph/69")
  SUBGRAPH_7_ @join__graph(name: "subgraph_7", url: "http://127.0.0.1:4001/subgraph/7")
  SUBGRAPH_70_ @join__graph(name: "subgraph_70", url: "http://127.0.0.1:4001/subgraph/70")
  SUBGRAPH_71_ @join__graph(name: "subgraph_71", url: "http://127.0.0.1:4001/subgraph/71")
  SUBGRAPH_72_ @join__graph(name: "subgraph_72", url: "http://127.0.0.1:4001/subgraph/72")
  SUBGRAPH_73_ @join__graph(name: "subgraph_73", url: "http://127.0.0.1:4001/subgraph/73")
  SUBGRAPH_74_ @join__graph(name: "subgraph_74", url: "http://127.0.0.1:4001/subgraph/74")
  SUBGRAPH_75_ @join__graph(name: "subgraph_75", url: "http://127.0.0.1:4001/subgraph/75")
  SUBGRAPH_76_ @join__graph(name: "subgraph_76", url: "http://127.0.0.1:4001/subgraph/76")
  SUBGRAPH_77_ @join__graph(name: "subgraph_77", url: "http://127.0.0.1:4001/subgraph/77")
  SUBGRAPH_78_ @join__graph(name: "subgraph_78", url: "http://127.0.0.1:4001/subgraph/78")
  SUBGRAPH_79_ @join__graph(name: "subgraph_79", url: "http://127.0.0.1:4001/subgraph/79")
  SUBGRAPH_8_ @join__graph(name: "subgraph_8", url: "http://127.0.0.1:4001/subgraph/8")
  SUBGRAPH_80_ @join__graph(name: "subgraph_80", url: "http://127.0.0.1:4001/subgraph/80")
  SUBGRAPH_81_ @join__graph(name: "subgraph_81", url: "http://127.0.0.1:4001/subgraph/81")
  SUBGRAPH_82_ @join__graph(name: "subgraph_82", url: "http://127.0.0.1:4001/subgraph/82")
  SUBGRAPH_83_ @join__graph(name: "subgraph_83", url: "http://127.0.0.1:4001/subgraph/83")
  SUBGRAPH_84_ @join__graph(name: "subgraph_84", url: "http://127.0.0.1:4001/subgraph/84")
  SUBGRAPH_85_ @join__graph(name: "subgraph_85", url: "http://127.0.0.1:4001/subgraph/85")
  SUBGRAPH_86_ @join__graph(name: "subgraph_86", url: "http://127.0.0.1:4001/subgraph/86")
  SUBGRAPH_87_ @join__graph(name: "subgraph_87", url: "http://127.0.0.1:4001/subgraph/87")
  SUBGRAPH_88_ @join__graph(name: "subgraph_88", url: "http://127.0.0.1:4001/subgraph/88")
  SUBGRAPH_89_ @join__graph(name: "subgraph_89", url: "http://127.0.0.1:4001/subgraph/89")
  SUBGRAPH_9_ @join__graph(name: "subgraph_9", url: "http://127.0.0.1:4001/subgraph/9")
  SUBGRAPH_90_ @join__graph(name: "subgraph_90", url: "http://127.0.0.1:4001/subgraph/90")
  SUBGRAPH_91_ @join__graph(name: "subgraph_91", url: "http://127.0.0.1:4001/subgraph/91")
  SUBGRAPH_92_ @join__graph(name: "subgraph_92", url: "http://127.0.0.1:4001/subgraph/92")
  SUBGRAPH_93_ @join__graph(name: "subgraph_93", url: "http://127.0.0.1:4001/subgraph/93")
  SUBGRAPH_94_ @join__graph(name: "subgraph_94", url: "http://127.0.0.1:4001/subgraph/94")
  SUBGRAPH_95_ @join__graph(name: "subgraph_95", url: "http://127.0.0.1:4001/subgraph/95")
  SUBGRAPH_96_ @join__graph(name: "subgraph_96", url: "http://127.0.0.1:4001/subgraph/96")
  SUBGRAPH_97_ @join__graph(name: "subgraph_97", url: "http://127.0.0.1:4001/subgraph/97")
  SUBGRAPH_98_ @join__graph(name: "subgraph_98", url: "http://127.0.0.1:4001/subgraph/98")
  SUBGRAPH_99_ @join__graph(name: "subgraph_99", url: "http://127.0.0.1:4001/subgraph/99")
}

scalar link__Import

enum link__Purpose {
  """
  `SECURITY` features provide metadata necessary to securely resolve fields.
  """
  SECURITY

  """
  `EXECUTION` features provide metadata necessary for operation execution.
  """
  EXECUTION
}

type Query
  @join__type(graph: SUBGRAPH_1_)
  @join__type(graph: SUBGRAPH_10_)
  @join__type(graph: SUBGRAPH_100_)
  @join__type(graph: SUBGRAPH_11_)
  @join__type(graph: SUBGRAPH_12_)
  @join__type(graph: SUBGRAPH_13_)
  @join__type(graph: SUBGRAPH_14_)
  @join__type(graph: SUBGRAPH_15_)
  @join__type(graph: SUBGRAPH_16_)
  @join__type(graph: SUBGRAPH_17_)
  @join__type(graph: SUBGRAPH_18_)
  @join__type(graph: SUBGRAPH_19_)
  @join__type(graph: SUBGRAPH_2_)
  @join__type(graph: SUBGRAPH_20_)
  @join__type(graph: SUBGRAPH_21_)
  @join__type(graph: SUBGRAPH_22_)
  @join__type(graph: SUBGRAPH_23_)
  @join__type(graph: SUBGRAPH_24_)
  @join__type(graph: SUBGRAPH_25_)
  @join__type(graph: SUBGRAPH_26_)
  @join__type(graph: SUBGRAPH_27_)
  @join__type(graph: SUBGRAPH_28_)
  @join__type(graph: SUBGRAPH_29_)
  @join__type(graph: SUBGRAPH_3_)
  @join__type(graph: SUBGRAPH_30_)
  @join__type(graph: SUBGRAPH_31_)
  @join__type(graph: SUBGRAPH_32_)
  @join__type(graph: SUBGRAPH_33_)
  @join__type(graph: SUBGRAPH_34_)
  @join__type(graph: SUBGRAPH_35_)
  @join__type(graph: SUBGRAPH_36_)
  @join__type(graph: SUBGRAPH_37_)
  @join__type(graph: SUBGRAPH_38_)
  @join__type(graph: SUBGRAPH_39_)
  @join__type(graph: SUBGRAPH_4_)
  @join__type(graph: SUBGRAPH_40_)
  @join__type(graph: SUBGRAPH_41_)
  @join__type(graph: SUBGRAPH_42_)
  @join__type(graph: SUBGRAPH_43_)
  @join__type(graph: SUBGRAPH_44_)
  @join__type(graph: SUBGRAPH_45_)
  @join__type(graph: SUBGRAPH_46_)
  @join__type(graph: SUBGRAPH_47_)
  @join__type(graph: SUBGRAPH_48_)
  @join__type(graph: SUBGRAPH_49_)
  @join__type(graph: SUBGRAPH_5_)
  @join__type(graph: SUBGRAPH_50_)
  @join__type(graph: SUBGRAPH_51_)
  @join__type(graph: SUBGRAPH_52_)
  @join__type(graph: SUBGRAPH_53_)
  @join__type(graph: SUBGRAPH_54_)
  @join__type(graph: SUBGRAPH_55_)
  @join__type(graph: SUBGRAPH_56_)
  @join__type(graph: SUBGRAPH_57_)
  @join__type(graph: SUBGRAPH_58_)
  @join__type(graph: SUBGRAPH_59_)
  @join__type(graph: SUBGRAPH_6_)
  @join__type(graph: SUBGRAPH_60_)
  @join__type(graph: SUBGRAPH_61_)
  @join__type(graph: SUBGRAPH_62_)
  @join__type(graph: SUBGRAPH_63_)
  @join__type(graph: SUBGRAPH_64_)
  @join__type(graph: SUBGRAPH_65_)
  @join__type(graph: SUBGRAPH_66_)
  @join__type(graph: SUBGRAPH_67_)
  @join__type(graph: SUBGRAPH_68_)
  @join__type(graph: SUBGRAPH_69_)
  @join__type(graph: SUBGRAPH_7_)
  @join__type(graph: SUBGRAPH_70_)
  @join__type(graph: SUBGRAPH_71_)
  @join__type(graph: SUBGRAPH_72_)
  @join__type(graph: SUBGRAPH_73_)
  @join__type(graph: SUBGRAPH_74_)
  @join__type(graph: SUBGRAPH_75_)
  @join__type(graph: SUBGRAPH_76_)
  @join__type(graph: SUBGRAPH_77_)
  @join__type(graph: SUBGRAPH_78_)
  @join__type(graph: SUBGRAPH_79_)
  @join__type(graph: SUBGRAPH_8_)
  @join__type(graph: SUBGRAPH_80_)
  @join__type(graph: SUBGRAPH_81_)
  @join__type(graph: SUBGRAPH_82_)
  @join__type(graph: SUBGRAPH_83_)
  @join__type(graph: SUBGRAPH_84_)
  @join__type(graph: SUBGRAPH_85_)
  @join__type(graph: SUBGRAPH_86_)
  @join__type(graph: SUBGRAPH_87_)
  @join__type(graph: SUBGRAPH_88_)
  @join__type(graph: SUBGRAPH_89_)
  @join__type(graph: SUBGRAPH_9_)
  @join__type(graph: SUBGRAPH_90_)
  @join__type(graph: SUBGRAPH_91_)
  @join__type(graph: SUBGRAPH_92_)
  @join__type(graph: SUBGRAPH_93_)
  @join__type(graph: SUBGRAPH_94_)
  @join__type(graph: SUBGRAPH_95_)
  @join__type(graph: SUBGRAPH_96_)
  @join__type(graph: SUBGRAPH_97_)
  @join__type(graph: SUBGRAPH_98_)
  @join__type(graph: SUBGRAPH_99_)
{
  user(id: ID!): User @join__field(graph: SUBGRAPH_1_)
  ping_1: String @join__field(graph: SUBGRAPH_1_)
  ping_10: String @join__field(graph: SUBGRAPH_10_)
  ping_100: String @join__field(graph: SUBGRAPH_100_)
  ping_11: String @join__field(graph: SUBGRAPH_11_)
  ping_12: String @join__field(graph: SUBGRAPH_12_)
  ping_13: String @join__field(graph: SUBGRAPH_13_)
  ping_14: String @join__field(graph: SUBGRAPH_14_)
  ping_15: String @join__field(graph: SUBGRAPH_15_)
  ping_16: String @join__field(graph: SUBGRAPH_16_)
  ping_17: String @join__field(graph: SUBGRAPH_17_)
  ping_18: String @join__field(graph: SUBGRAPH_18_)
  ping_19: String @join__field(graph: SUBGRAPH_19_)
  ping_2: String @join__field(graph: SUBGRAPH_2_)
  ping_20: String @join__field(graph: SUBGRAPH_20_)
  ping_21: String @join__field(graph: SUBGRAPH_21_)
  ping_22: String @join__field(graph: SUBGRAPH_22_)
  ping_23: String @join__field(graph: SUBGRAPH_23_)
  ping_24: String @join__field(graph: SUBGRAPH_24_)
  ping_25: String @join__field(graph: SUBGRAPH_25_)
  ping_26: String @join__field(graph: SUBGRAPH_26_)
  ping_27: String @join__field(graph: SUBGRAPH_27_)
  ping_28: String @join__field(graph: SUBGRAPH_28_)
  ping_29: String @join__field(graph: SUBGRAPH_29_)
  ping_3: String @join__field(graph: SUBGRAPH_3_)
  ping_30: String @join__field(graph: SUBGRAPH_30_)
  ping_31: String @join__field(graph: SUBGRAPH_31_)
  ping_32: String @join__field(graph: SUBGRAPH_32_)
  ping_33: String @join__field(graph: SUBGRAPH_33_)
  ping_34: String @join__field(graph: SUBGRAPH_34_)
  ping_35: String @join__field(graph: SUBGRAPH_35_)
  ping_36: String @join__field(graph: SUBGRAPH_36_)
  ping_37: String @join__field(graph: SUBGRAPH_37_)
  ping_38: String @join__field(graph: SUBGRAPH_38_)
  ping_39: String @join__field(graph: SUBGRAPH_39_)
  ping_4: String @join__field(graph: SUBGRAPH_4_)
  ping_40: String @join__field(graph: SUBGRAPH_40_)
  ping_41: String @join__field(graph: SUBGRAPH_41_)
  ping_42: String @join__field(graph: SUBGRAPH_42_)
  ping_43: String @join__field(graph: SUBGRAPH_43_)
  ping_44: String @join__field(graph: SUBGRAPH_44_)
  ping_45: String @join__field(graph: SUBGRAPH_45_)
  ping_46: String @join__field(graph: SUBGRAPH_46_)
  ping_47: String @join__field(graph: SUBGRAPH_47_)
  ping_48: String @join__field(graph: SUBGRAPH_48_)
  ping_49: String @join__field(graph: SUBGRAPH_49_)
  ping_5: String @join__field(graph: SUBGRAPH_5_)
  ping_50: String @join__field(graph: SUBGRAPH_50_)
  ping_51: String @join__field(graph: SUBGRAPH_51_)
  ping_52: String @join__field(graph: SUBGRAPH_52_)
  ping_53: String @join__field(graph: SUBGRAPH_53_)
  ping_54: String @join__field(graph: SUBGRAPH_54_)
  ping_55: String @join__field(graph: SUBGRAPH_55_)
  ping_56: String @join__field(graph: SUBGRAPH_56_)
  ping_57: String @join__field(graph: SUBGRAPH_57_)
  ping_58: String @join__field(graph: SUBGRAPH_58_)
  ping_59: String @join__field(graph: SUBGRAPH_59_)
  ping_6: String @join__field(graph: SUBGRAPH_6_)
  ping_60: String @join__field(graph: SUBGRAPH_60_)
  ping_61: String @join__field(graph: SUBGRAPH_61_)
  ping_62: String @join__field(graph: SUBGRAPH_62_)
  ping_63: String @join__field(graph: SUBGRAPH_63_)
  ping_64: String @join__field(graph: SUBGRAPH_64_)
  ping_65: String @join__field(graph: SUBGRAPH_65_)
  ping_66: String @join__field(graph: SUBGRAPH_66_)
  ping_67: String @join__field(graph: SUBGRAPH_67_)
  ping_68: String @join__field(graph: SUBGRAPH_68_)
  ping_69: String @join__field(graph: SUBGRAPH_69_)
  ping_7: String @join__field(graph: SUBGRAPH_7_)
  ping_70: String @join__field(graph: SUBGRAPH_70_)
  ping_71: String @join__field(graph: SUBGRAPH_71_)
  ping_72: String @join__field(graph: SUBGRAPH_72_)
  ping_73: String @join__field(graph: SUBGRAPH_73_)
  ping_74: String @join__field(graph: SUBGRAPH_74_)
  ping_75: String @join__field(graph: SUBGRAPH_75_)
  ping_76: String @join__field(graph: SUBGRAPH_76_)
  ping_77: String @join__field(graph: SUBGRAPH_77_)
  ping_78: String @join__field(graph: SUBGRAPH_78_)
  ping_79: String @join__field(graph: SUBGRAPH_79_)
  ping_8: String @join__field(graph: SUBGRAPH_8_)
  ping_80: String @join__field(graph: SUBGRAPH_80_)
  ping_81: String @join__field(graph: SUBGRAPH_81_)
  ping_82: String @join__field(graph: SUBGRAPH_82_)
  ping_83: String @join__field(graph: SUBGRAPH_83_)
  ping_84: String @join__field(graph: SUBGRAPH_84_)
  ping_85: String @join__field(graph: SUBGRAPH_85_)
  ping_86: String @join__field(graph: SUBGRAPH_86_)
  ping_87: String @join__field(graph: SUBGRAPH_87_)
  ping_88: String @join__field(graph: SUBGRAPH_88_)
  ping_89: String @join__field(graph: SUBGRAPH_89_)
  ping_9: String @join__field(graph: SUBGRAPH_9_)
  ping_90: String @join__field(graph: SUBGRAPH_90_)
  ping_91: String @join__field(graph: SUBGRAPH_91_)
  ping_92: String @join__field(graph: SUBGRAPH_92_)
  ping_93: String @join__field(graph: SUBGRAPH_93_)
  ping_94: String @join__field(graph: SUBGRAPH_94_)
  ping_95: String @join__field(graph: SUBGRAPH_95_)
  ping_96: String @join__field(graph: SUBGRAPH_96_)
  ping_97: String @join__field(graph: SUBGRAPH_97_)
  ping_98: String @join__field(graph: SUBGRAPH_98_)
  ping_99: String @join__field(graph: SUBGRAPH_99_)
}

type User
  @join__type(graph: SUBGRAPH_1_, key: "id")
  @join__type(graph: SUBGRAPH_10_, key: "id")
  @join__type(graph: SUBGRAPH_100_, key: "id")
  @join__type(graph: SUBGRAPH_11_, key: "id")
  @join__type(graph: SUBGRAPH_12_, key: "id")
  @join__type(graph: SUBGRAPH_13_, key: "id")
  @join__type(graph: SUBGRAPH_14_, key: "id")
  @join__type(graph: SUBGRAPH_15_, key: "id")
  @join__type(graph: SUBGRAPH_16_, key: "id")
  @join__type(graph: SUBGRAPH_17_, key: "id")
  @join__type(graph: SUBGRAPH_18_, key: "id")
  @join__type(graph: SUBGRAPH_19_, key: "id")
  @join__type(graph: SUBGRAPH_2_, key: "id")
  @join__type(graph: SUBGRAPH_20_, key: "id")
  @join__type(graph: SUBGRAPH_21_, key: "id")
  @join__type(graph: SUBGRAPH_22_, key: "id")
  @join__type(graph: SUBGRAPH_23_, key: "id")
  @join__type(graph: SUBGRAPH_24_, key: "id")
  @join__type(graph: SUBGRAPH_25_, key: "id")
  @join__type(graph: SUBGRAPH_26_, key: "id")
  @join__type(graph: SUBGRAPH_27_, key: "id")
  @join__type(graph: SUBGRAPH_28_, key: "id")
  @join__type(graph: SUBGRAPH_29_, key: "id")
  @join__type(graph: SUBGRAPH_3_, key: "id")
  @join__type(graph: SUBGRAPH_30_, key: "id")
  @join__type(graph: SUBGRAPH_31_, key: "id")
  @join__type(graph: SUBGRAPH_32_, key: "id")
  @join__type(graph: SUBGRAPH_33_, key: "id")
  @join__type(graph: SUBGRAPH_34_, key: "id")
  @join__type(graph: SUBGRAPH_35_, key: "id")
  @join__type(graph: SUBGRAPH_36_, key: "id")
  @join__type(graph: SUBGRAPH_37_, key: "id")
  @join__type(graph: SUBGRAPH_38_, key: "id")
  @join__type(graph: SUBGRAPH_39_, key: "id")
  @join__type(graph: SUBGRAPH_4_, key: "id")
  @join__type(graph: SUBGRAPH_40_, key: "id")
  @join__type(graph: SUBGRAPH_41_, key: "id")
  @join__type(graph: SUBGRAPH_42_, key: "id")
  @join__type(graph: SUBGRAPH_43_, key: "id")
  @join__type(graph: SUBGRAPH_44_, key: "id")
  @join__type(graph: SUBGRAPH_45_, key: "id")
  @join__type(graph: SUBGRAPH_46_, key: "id")
  @join__type(graph: SUBGRAPH_47_, key: "id")
  @join__type(graph: SUBGRAPH_48_, key: "id")
  @join__type(graph: SUBGRAPH_49_, key: "id")
  @join__type(graph: SUBGRAPH_5_, key: "id")
  @join__type(graph: SUBGRAPH_50_, key: "id")
  @join__type(graph: SUBGRAPH_51_, key: "id")
  @join__type(graph: SUBGRAPH_52_, key: "id")
  @join__type(graph: SUBGRAPH_53_, key: "id")
  @join__type(graph: SUBGRAPH_54_, key: "id")
  @join__type(graph: SUBGRAPH_55_, key: "id")
  @join__type(graph: SUBGRAPH_56_, key: "id")
  @join__type(graph: SUBGRAPH_57_, key: "id")
  @join__type(graph: SUBGRAPH_58_, key: "id")
  @join__type(graph: SUBGRAPH_59_, key: "id")
  @join__type(graph: SUBGRAPH_6_, key: "id")
  @join__type(graph: SUBGRAPH_60_, key: "id")
  @join__type(graph: SUBGRAPH_61_, key: "id")
  @join__type(graph: SUBGRAPH_62_, key: "id")
  @join__type(graph: SUBGRAPH_63_, key: "id")
  @join__type(graph: SUBGRAPH_64_, key: "id")
  @join__type(graph: SUBGRAPH_65_, key: "id")
  @join__type(graph: SUBGRAPH_66_, key: "id")
  @join__type(graph: SUBGRAPH_67_, key: "id")
  @join__type(graph: SUBGRAPH_68_, key: "id")
  @join__type(graph: SUBGRAPH_69_, key: "id")
  @join__type(graph: SUBGRAPH_7_, key: "id")
  @join__type(graph: SUBGRAPH_70_, key: "id")
  @join__type(graph: SUBGRAPH_71_, key: "id")
  @join__type(graph: SUBGRAPH_72_, key: "id")
  @join__type(graph: SUBGRAPH_73_, key: "id")
  @join__type(graph: SUBGRAPH_74_, key: "id")
  @join__type(graph: SUBGRAPH_75_, key: "id")
  @join__type(graph: SUBGRAPH_76_, key: "id")
  @join__type(graph: SUBGRAPH_77_, key: "id")
  @join__type(graph: SUBGRAPH_78_, key: "id")
  @join__type(graph: SUBGRAPH_79_, key: "id")
  @join__type(graph: SUBGRAPH_8_, key: "id")
  @join__type(graph: SUBGRAPH_80_, key: "id")
  @join__type(graph: SUBGRAPH_81_, key: "id")
  @join__type(graph: SUBGRAPH_82_, key: "id")
  @join__type(graph: SUBGRAPH_83_, key: "id")
  @join__type(graph: SUBGRAPH_84_, key: "id")
  @join__type(graph: SUBGRAPH_85_, key: "id")
  @join__type(graph: SUBGRAPH_86_, key: "id")
  @join__type(graph: SUBGRAPH_87_, key: "id")
  @join__type(graph: SUBGRAPH_88_, key: "id")
  @join__type(graph: SUBGRAPH_89_, key: "id")
  @join__type(graph: SUBGRAPH_9_, key: "id")
  @join__type(graph: SUBGRAPH_90_, key: "id")
  @join__type(graph: SUBGRAPH_91_, key: "id")
  @join__type(graph: SUBGRAPH_92_, key: "id")
  @join__type(graph: SUBGRAPH_93_, key: "id")
  @join__type(graph: SUBGRAPH_94_, key: "id")
  @join__type(graph: SUBGRAPH_95_, key: "id")
  @join__type(graph: SUBGRAPH_96_, key: "id")
  @join__type(graph: SUBGRAPH_97_, key: "id")
  @join__type(graph: SUBGRAPH_98_, key: "id")
  @join__type(graph: SUBGRAPH_99_, key: "id")
{
  id: ID!
  name: String @join__field(graph: SUBGRAPH_1_)
  field_1: String @join__field(graph: SUBGRAPH_1_)
  field_10: String @join__field(graph: SUBGRAPH_10_)
  field_100: String @join__field(graph: SUBGRAPH_100_)
  field_11: String @join__field(graph: SUBGRAPH_11_)
  field_12: String @join__field(graph: SUBGRAPH_12_)
  field_13: String @join__field(graph: SUBGRAPH_13_)
  field_14: String @join__field(graph: SUBGRAPH_14_)
  field_15: String @join__field(graph: SUBGRAPH_15_)
  field_16: String @join__field(graph: SUBGRAPH_16_)
  field_17: String @join__field(graph: SUBGRAPH_17_)
  field_18: String @join__field(graph: SUBGRAPH_18_)
  field_19: String @join__field(graph: SUBGRAPH_19_)
  field_2: String @join__field(graph: SUBGRAPH_2_)
  field_20: String @join__field(graph: SUBGRAPH_20_)
  field_21: String @join__field(graph: SUBGRAPH_21_)
  field_22: String @join__field(graph: SUBGRAPH_22_)
  field_23: String @join__field(graph: SUBGRAPH_23_)
  field_24: String @join__field(graph: SUBGRAPH_24_)
  field_25: String @join__field(graph: SUBGRAPH_25_)
  field_26: String @join__field(graph: SUBGRAPH_26_)
  field_27: String @join__field(graph: SUBGRAPH_27_)
  field_28: String @join__field(graph: SUBGRAPH_28_)
  field_29: String @join__field(graph: SUBGRAPH_29_)
  field_3: String @join__field(graph: SUBGRAPH_3_)
  field_30: String @join__field(graph: SUBGRAPH_30_)
  field_31: String @join__field(graph: SUBGRAPH_31_)
  field_32: String @join__field(graph: SUBGRAPH_32_)
  field_33: String @join__field(graph: SUBGRAPH_33_)
  field_34: String @join__field(graph: SUBGRAPH_34_)
  field_35: String @join__field(graph: SUBGRAPH_35_)
  field_36: String @join__field(graph: SUBGRAPH_36_)
  field_37: String @join__field(graph: SUBGRAPH_37_)
  field_38: String @join__field(graph: SUBGRAPH_38_)
  field_39: String @join__field(graph: SUBGRAPH_39_)
  field_4: String @join__field(graph: SUBGRAPH_4_)
  field_40: String @join__field(graph: SUBGRAPH_40_)
  field_41: String @join__field(graph: SUBGRAPH_41_)
  field_42: String @join__field(graph: SUBGRAPH_42_)
  field_43: String @join__field(graph: SUBGRAPH_43_)
  field_44: String @join__field(graph: SUBGRAPH_44_)
  field_45: String @join__field(graph: SUBGRAPH_45_)
  field_46: String @join__field(graph: SUBGRAPH_46_)
  field_47: String @join__field(graph: SUBGRAPH_47_)
  field_48: String @join__field(graph: SUBGRAPH_48_)
  field_49: String @join__field(graph: SUBGRAPH_49_)
  field_5: String @join__field(graph: SUBGRAPH_5_)
  field_50: String @join__field(graph: SUBGRAPH_50_)
  field_51: String @join__field(graph: SUBGRAPH_51_)
  field_52: String @join__field(graph: SUBGRAPH_52_)
  field_53: String @join__field(graph: SUBGRAPH_53_)
  field_54: String @join__field(graph: SUBGRAPH_54_)
  field_55: String @join__field(graph: SUBGRAPH_55_)
  field_56: String @join__field(graph: SUBGRAPH_56_)
  field_57: String @join__field(graph: SUBGRAPH_57_)
  field_58: String @join__field(graph: SUBGRAPH_58_)
  field_59: String @join__field(graph: SUBGRAPH_59_)
  field_6: String @join__field(graph: SUBGRAPH_6_)
  field_60: String @join__field(graph: SUBGRAPH_60_)
  field_61: String @join__field(graph: SUBGRAPH_61_)
  field_62: String @join__field(graph: SUBGRAPH_62_)
  field_63: String @join__field(graph: SUBGRAPH_63_)
  field_64: String @join__field(graph: SUBGRAPH_64_)
  field_65: String @join__field(graph: SUBGRAPH_65_)
  field_66: String @join__field(graph: SUBGRAPH_66_)
  field_67: String @join__field(graph: SUBGRAPH_67_)
  field_68: String @join__field(graph: SUBGRAPH_68_)
  field_69: String @join__field(graph: SUBGRAPH_69_)
  field_7: String @join__field(graph: SUBGRAPH_7_)
  field_70: String @join__field(graph: SUBGRAPH_70_)
  field_71: String @join__field(graph: SUBGRAPH_71_)
  field_72: String @join__field(graph: SUBGRAPH_72_)
  field_73: String @join__field(graph: SUBGRAPH_73_)
  field_74: String @join__field(graph: SUBGRAPH_74_)
  field_75: String @join__field(graph: SUBGRAPH_75_)
  field_76: String @join__field(graph: SUBGRAPH_76_)
  field_77: String @join__field(graph: SUBGRAPH_77_)
  field_78: String @join__field(graph: SUBGRAPH_78_)
  field_79: String @join__field(graph: SUBGRAPH_79_)
  field_8: String @join__field(graph: SUBGRAPH_8_)
  field_80: String @join__field(graph: SUBGRAPH_80_)
  field_81: String @join__field(graph: SUBGRAPH_81_)
  field_82: String @join__field(graph: SUBGRAPH_82_)
  field_83: String @join__field(graph: SUBGRAPH_83_)
  field_84: String @join__field(graph: SUBGRAPH_84_)
  field_85: String @join__field(graph: SUBGRAPH_85_)
  field_86: String @join__field(graph: SUBGRAPH_86_)
  field_87: String @join__field(graph: SUBGRAPH_87_)
  field_88: String @join__field(graph: SUBGRAPH_88_)
  field_89: String @join__field(graph: SUBGRAPH_89_)
  field_9: String @join__field(graph: SUBGRAPH_9_)
  field_90: String @join__field(graph: SUBGRAPH_90_)
  field_91: String @join__field(graph: SUBGRAPH_91_)
  field_92: String @join__field(graph: SUBGRAPH_92_)
  field_93: String @join__field(graph: SUBGRAPH_93_)
  field_94: String @join__field(graph: SUBGRAPH_94_)
  field_95: String @join__field(graph: SUBGRAPH_95_)
  field_96: String @join__field(graph: SUBGRAPH_96_)
  field_97: String @join__field(graph: SUBGRAPH_97_)
  field_98: String @join__field(graph: SUBGRAPH_98_)
  field_99: String @join__field(graph: SUBGRAPH_99_)
}
